# Generated by Django 5.0.2 on 2024-04-07 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('school_unit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='school_unit.schoolunit', verbose_name='Unidade Escolar')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Produto')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='stock.stock', verbose_name='Estoque')),
            ],
            options={
                'verbose_name': 'Item do Estoque',
                'verbose_name_plural': 'Itens do Estoque',
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('transfer_date', models.DateTimeField(auto_now=True, verbose_name='Data de Tranferência')),
                ('origin_school_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_transfers', to='school_unit.schoolunit', verbose_name='Estoque de Origem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Produto')),
                ('target_school_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_transfers', to='school_unit.schoolunit', verbose_name='Estoque de Destino')),
                ('transferred_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Transferido por')),
            ],
            options={
                'verbose_name': 'Tranferência de Estoque',
                'verbose_name_plural': 'Tranferências de Estoques',
            },
        ),
    ]
