# Generated by Django 5.0.2 on 2024-03-18 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='school_unit',
        ),
    ]
