# Generated by Django 5.0.2 on 2024-03-19 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_unit', '0002_remove_schoolunit_stock'),
        ('stock', '0002_remove_stock_school_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='school_unit',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='school_unit.schoolunit', verbose_name='Unidade Escolar'),
            preserve_default=False,
        ),
    ]
