# Generated by Django 5.0.2 on 2024-03-20 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_unit', '0002_remove_schoolunit_stock'),
        ('stock', '0003_stock_school_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='school_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='school_unit.schoolunit', verbose_name='Unidade Escolar'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='stock.stock', verbose_name='Estoque'),
        ),
    ]
