# Generated by Django 5.0.2 on 2024-03-30 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_created_at_alter_product_created_by_and_more'),
        ('school_unit', '0003_schoolunit_main_unit'),
        ('stock', '0004_alter_stock_school_unit_alter_stockitem_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('transfer_date', models.DateTimeField(auto_now=True, verbose_name='Data de Tranferência')),
                ('origin_school_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_transfers', to='school_unit.schoolunit', verbose_name='Estoque de Origem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Produto')),
                ('target_school_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_transfers', to='school_unit.schoolunit', verbose_name='Estoque de Destino')),
                ('transferred_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Transferido por')),
            ],
            options={
                'verbose_name': 'Tranferência de Estoque',
                'verbose_name_plural': 'Tranferências de Estoques',
            },
        ),
    ]
