# Generated by Django 5.0.2 on 2024-04-12 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_name'),
        ('school_unit', '0001_initial'),
        ('stock', '0004_alter_stockitem_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='origin_school_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_transfers', to='school_unit.schoolunit', verbose_name='Estoque de Origem'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='target_school_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_transfers', to='school_unit.schoolunit', verbose_name='Estoque de Destino'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='transferred_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Transferido por'),
        ),
    ]
