# Generated by Django 5.0.2 on 2024-04-12 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stocktransfer_origin_school_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.stock', verbose_name='Estoque'),
        ),
    ]
