# Generated by Django 5.0.2 on 2024-03-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stocktransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
    ]
