# Generated by Django 5.0.2 on 2024-03-13 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('unit_type', models.CharField(choices=[('U', 'Unidade'), ('M', 'Metro'), ('P', 'Pacote'), ('B', 'Bloco'), ('C', 'Caixa'), ('R', 'Rolo')], max_length=1, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
