# Generated by Django 5.0.2 on 2024-03-18 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0002_remove_stock_school_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='school_unit', to='stock.stock', verbose_name='Estoque')),
            ],
            options={
                'verbose_name': 'Unidade Escolar',
                'verbose_name_plural': 'Unidades Escolares',
            },
        ),
    ]
