# Generated by Django 5.0.2 on 2024-03-19 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_unit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolunit',
            name='stock',
        ),
    ]
