# Generated by Django 5.0.2 on 2024-03-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_unit', '0002_remove_schoolunit_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolunit',
            name='main_unit',
            field=models.BooleanField(default=False, verbose_name='Unidade Escolar Principal'),
        ),
    ]
