name: Build and Test

on:
  push:
    branches:
      - main

env: 
  CE_SECRET_KEY: ${{ vars.CE_SECRET_KEY }}
  CE_DB_USERNAME: ${{ vars.CE_DB_USERNAME }}
  CE_DB_PASSWORD: ${{ vars.CE_DB_PASSWORD }}
  CE_DB_NAME: ${{ vars.CE_DB_NAME }}
  CE_DB_HOSTNAME: ${{ vars.CE_DB_HOSTNAME }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: mirromutth/mysql-action@v1.1
      with:
          mysql database: ${{ vars.CE_DB_NAME }}
          mysql root password: ${{ vars.CE_DB_PASSWORD }}
        
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo $CE_DB_USERNAME
        echo $CE_DB_PASSWORD

    - name: Run Django migrations
      run: |
        python manage.py migrate

    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput

    - name: Run unit tests
      run: |
        python manage.py test
