name: Deploy to Azure

on:
  push:
    branches:
      - main

env: 
  CE_SECRET_KEY: ${{ vars.CE_SECRET_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Teste
      run: echo ${{ vars.CE_SECRET_KEY }}
      
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        echo $CE_SECRET_KEY
        echo "teste"
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django migrations
      run: |
        python manage.py migrate

    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput
