name: Deploy to Azure

on:
  push:
    branches:
      - main

env: 
  CE_SECRET_KEY: ${{ secrets.CE_SECRET_KEY }}
  CE_DB_USERNAME: ${{ secrets.CE_DB_USERNAME }}
  CE_DB_PASSWORD: ${{ secrets.CE_DB_PASSWORD }}
  CE_DB_NAME: ${{ secrets.CE_DB_NAME }}
  CE_DB_HOSTNAME: ${{ SECRETS.CE_DB_HOSTNAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.CE_DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.CE_DB_NAME }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
    - name: Verificar host e permissões do MySQL
      run: |
        mysql -h ${{ SECRETS.CE_DB_HOSTNAME }} -u root -p"${{ secrets.CE_DB_PASSWORD }}" -e "CREATE USER '${{ secrets.CE_DB_USERNAME }}'@'${{ SECRETS.CE_DB_HOSTNAME }}' IDENTIFIED BY '${{ secrets.CE_DB_USER_PASSWORD }}';"
        
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django migrations
      run: |
        python manage.py migrate

    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput
